# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Running Test
    runs-on: ubuntu-latest

    steps:
      - name: github-status-action
        uses: Sibz/github-status-action@v1.1.1
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: install
        run: mvn install -DskipTests=true
      - name: install
        run: mvn test
